# Generated by Django 4.2.4 on 2023-08-27 06:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='city',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('city_name', models.CharField(blank=None, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='countryCode',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('iso_id', models.CharField(blank=None, max_length=3, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='pincode',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('pin_code', models.CharField(max_length=15, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='state',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('state_name', models.CharField(blank=None, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='address',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('line1', models.TextField()),
                ('line2', models.TextField()),
                ('is_default', models.BooleanField(default=True)),
                ('home_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.city')),
                ('home_country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.countrycode')),
                ('home_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.state')),
                ('pin_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.pincode')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
